### ISSUE TITLE
Lexical_cast throws an error converting string "08" to int128_t

### ISSUE THREAD

**Issue by ProfChris** [boostorg/lexical_cast#48]
Using boost library 1_76_0 the following C++ program throws an exception.  
#include <iostream>

#include <boost/multiprecision/cpp_int.hpp>
#include <boost/lexical_cast.hpp>

using namespace std;
using namespace boost::multiprecision;

int main()
{
		int128_t r_number;		
		string reverse_number = "08";
		r_number = boost::lexical_cast<int128_t>(reverse_number); 
		cout << r_number;
}

other strings i.e "02", "03" etc convert successfully. 
I solved my problem by removing leading zeros prior to conversion.

**Comment by pdimov** [comment]
The reason this happens is that numbers starting with 0 are interpreted as octal by Multiprecision's `operator>>`. So, for instance, the string `012` is interpreted as 10. `08` is rejected because it's not a valid octal number. See https://godbolt.org/z/1zc3qdn3c.

Since this behavior comes from Multiprecision's `operator>>`, it's not a `lexical_cast` issue and should be reported to Multiprecision in case the behavior isn't by design.
